resources:
- namespaces.yaml
helmCharts:
- name: kube-prometheus-stack
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  namespace: prometheus-system
  includeCRDs: true
  version: 73.2.0
  valuesFile: values-kube-prometheus-stack.yaml
- name: loki-stack
  repo: https://grafana.github.io/helm-charts
  releaseName: loki-stack
  namespace: loki-system
  version: 2.10.2
- name: tempo
  repo: https://grafana.github.io/helm-charts
  releaseName: tempo
  namespace: tempo-system
  version: 1.21.1
